// Arti nama surah dalam Bahasa Indonesia
export const SURAH_MEANING_ID = {
  1:   'Pembuka',
  2:   'Sapi Betina',
  3:   'Keluarga Imran',
  4:   'Wanita',
  5:   'Hidangan',
  6:   'Binatang Ternak',
  7:   'Tempat Tertinggi',
  8:   'Rampasan Perang',
  9:   'Pengampunan',
  10:  'Nabi Yunus',
  11:  'Nabi Hud',
  12:  'Nabi Yusuf',
  13:  'Guruh',
  14:  'Nabi Ibrahim',
  15:  'Al-Hijr',
  16:  'Lebah',
  17:  'Perjalanan Malam',
  18:  'Gua',
  19:  'Maryam',
  20:  'Ta Ha',
  21:  'Para Nabi',
  22:  'Haji',
  23:  'Orang-Orang Beriman',
  24:  'Cahaya',
  25:  'Pembeda',
  26:  'Para Penyair',
  27:  'Semut',
  28:  'Kisah-Kisah',
  29:  'Laba-Laba',
  30:  'Bangsa Romawi',
  31:  'Luqman',
  32:  'Sujud',
  33:  'Golongan-Golongan',
  34:  'Saba',
  35:  'Pencipta',
  36:  'Ya Sin',
  37:  'Yang Berbaris',
  38:  'Sad',
  39:  'Rombongan',
  40:  'Yang Maha Pengampun',
  41:  'Yang Dijelaskan',
  42:  'Musyawarah',
  43:  'Perhiasan',
  44:  'Asap',
  45:  'Yang Berlutut',
  46:  'Bukit-Bukit Pasir',
  47:  'Muhammad',
  48:  'Kemenangan',
  49:  'Kamar-Kamar',
  50:  'Qaf',
  51:  'Angin Yang Menerbangkan',
  52:  'Bukit Sinai',
  53:  'Bintang',
  54:  'Bulan',
  55:  'Yang Maha Pengasih',
  56:  'Hari Kiamat',
  57:  'Besi',
  58:  'Wanita Yang Mengajukan Gugatan',
  59:  'Pengusiran',
  60:  'Wanita Yang Diuji',
  61:  'Barisan',
  62:  'Hari Jumat',
  63:  'Orang-Orang Munafik',
  64:  'Hari Ditampakkan Kesalahan',
  65:  'Talak',
  66:  'Mengharamkan',
  67:  'Kerajaan',
  68:  'Pena',
  69:  'Hari Kiamat Yang Pasti',
  70:  'Tempat-Tempat Naik',
  71:  'Nabi Nuh',
  72:  'Jin',
  73:  'Orang Yang Berselimut',
  74:  'Orang Yang Berkemul',
  75:  'Hari Kebangkitan',
  76:  'Manusia',
  77:  'Malaikat Yang Diutus',
  78:  'Berita Besar',
  79:  'Malaikat Yang Mencabut',
  80:  'Ia Bermuka Masam',
  81:  'Menggulung',
  82:  'Terbelah',
  83:  'Orang Yang Curang',
  84:  'Terbelah',
  85:  'Gugusan Bintang',
  86:  'Yang Datang Di Malam Hari',
  87:  'Yang Paling Tinggi',
  88:  'Hari Pembalasan',
  89:  'Fajar',
  90:  'Negeri',
  91:  'Matahari',
  92:  'Malam',
  93:  'Waktu Duha',
  94:  'Melapangkan',
  95:  'Buah Tin',
  96:  'Segumpal Darah',
  97:  'Kemuliaan',
  98:  'Bukti Yang Nyata',
  99:  'Kegoncangan',
  100: 'Kuda Yang Berlari',
  101: 'Hari Kiamat',
  102: 'Bermegah-Megahan',
  103: 'Masa',
  104: 'Pengumpat',
  105: 'Gajah',
  106: 'Suku Quraisy',
  107: 'Barang Yang Berguna',
  108: 'Nikmat Yang Berlimpah',
  109: 'Orang-Orang Kafir',
  110: 'Pertolongan',
  111: 'Sabut',
  112: 'Ikhlas',
  113: 'Waktu Subuh',
  114: 'Manusia',
};
